name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Using GitHub Secrets
      APP_MODE: "production"  # Example custom environment variable
    
    steps:
      - name: Debug Environment Variables
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Checking if OPENAI_API_KEY is set"
          echo "API Key length: ${#OPENAI_API_KEY}"
        shell: bash
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyaudio pyautogui pyqt6 speechrecognition openai httpx soundfile python-dotenv
        #pip install pyinstaller pyaudio pyautogui pyqt6 speechrecognition openai-whisper soundfile

      # Step 4: Get Whisper's installed path dynamically
      # - name: Find Whisper Path
      # id: whisper_path
      # run: |
      # echo "WHISPER_PATH=$(python -c 'import whisper, os; print(os.path.dirname(whisper.__file__))')" >> $GITHUB_ENV
      # shell: bash

      # Step 5: Build the executable with PyInstaller
      # pyinstaller --noconfirm --onedir --windowed --collect-submodules=numba --recursive-copy-metadata="openai-whisper" --add-data="%WHISPER_PATH%;whisper/" main.py
      - name: Build executable
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pyinstaller --noconfirm --onedir --collect-submodules=numba main.py
      
        shell: cmd

      # Step 6: Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/
