name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Step 4: Build the executable with PyInstaller
      - name: Build executable
        run: |
          pyinstaller --onefile main.py
        shell: cmd

      # Step 5: Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist/main.exe
